### ISSUE TITLE
Error: react-universal-blog@1.0.0 development: `cp views/index.html public/index.html && NODE_ENV=development webpack && npm run webpack-dev-server`

### ISSUE THREAD

**Issue by exdestroyer** [tonyspiro/react-universal-blog#3]
When I run the npm script, it informs this error with my Node.js v6.4.0

**Comment by tonyspiro** [comment]
Are you running this on Windows?

**Comment by exdestroyer** [comment]
yes, I am running on windows

**Comment by tonyspiro** [comment]
Ok there are a few gotchas with running env var commands on Windows.  This may help http://stackoverflow.com/questions/9249830/how-can-i-set-node-env-production-in-windows
